project_id = "lbyyogrfzwxhlbcdfhqz"

[api]
enabled = true
port = 8000
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
host = "db.lbyyogrfzwxhlbcdfhqz.supabase.co"
user = "postgres"
password = "eIzewIQm1crwhOEG"
name = "postgres"
max_connections = 100

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 30
max_client_conn = 200

[realtime]
enabled = true
ip_version = "ipv6"
port = 54324
max_events = 100

[studio]
enabled = true
port = 3000
api_url = "https://api.agendopro.com.br"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327
smtp_ssl = true

[storage]
enabled = true
port = 54326
file_size_limit = "100MiB"
upload_limit_per_day = "1GiB"
allowed_mime_types = [
  "image/jpeg",
  "image/png",
  "image/gif",
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
cookie_options = {
  same_site = "lax",
  secure = true,
  http_only = true
}

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
min_password_length = 10
disable_weak_passwords = true
mailer_autoconfirm = false
mailer_secure_email_change_enabled = true
smtp_admin_email = "suporte@agendopro.com.br"
smtp_max_frequency = 60

[auth.external]
google_enabled = true
facebook_enabled = true
apple_enabled = true

[functions]
verify_jwt = true
invoke_timeout_seconds = 60
import_map_path = "import_map.json"
environment = [
  { name = "ENVIRONMENT", value = "production" },
  { name = "API_URL", value = "https://api.agendopro.com.br" }
]

[analytics]
enabled = true
port = 54328
vector_enabled = true

[services]
[services.postgres]
port = 5432
[services.studio]
port = 3000
