// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxrpwfmqnwspvhgswatr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cnB3Zm1xbndzcHZoZ3N3YXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTc5NTksImV4cCI6MjA2NDA5Mzk1OX0.ah_ruGtlUXZ2jzcCRHvbu0m1Ur3_uMCMJ8dVu5uiZqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);