// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbyyogrfzwxhlbcdfhqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxieXlvZ3Jmend4aGxiY2RmaHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTEzMzIsImV4cCI6MjA2NDE4NzMzMn0.FkrELyaJXrEZHDh-mdIdE1_B_9IRNPbTN1wpsQyrGKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public'
  },
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});